/**
 * Normalise les noms d'ingrédients vers une forme canonique française.
 * Gère : anglicismes, synonymes courants, variantes orthographiques.
 */

// Clé : variante en minuscules → valeur : nom canonique français
const SYNONYMS = {
  // --- Anglicismes fréquents ---
  "chicken": "poulet",
  "beef": "bœuf",
  "pork": "porc",
  "lamb": "agneau",
  "veal": "veau",
  "turkey": "dinde",
  "salmon": "saumon",
  "tuna": "thon",
  "shrimp": "crevettes",
  "cod": "cabillaud",
  "egg": "œuf",
  "eggs": "œufs",
  "milk": "lait",
  "butter": "beurre",
  "cheese": "fromage",
  "cream": "crème",
  "yogurt": "yaourt",
  "yoghurt": "yaourt",
  "wheat": "blé",
  "wheat flour": "farine de blé",
  "flour": "farine",
  "sugar": "sucre",
  "salt": "sel",
  "pepper": "poivre",
  "garlic": "ail",
  "onion": "oignon",
  "tomato": "tomate",
  "tomatoes": "tomate",
  "potato": "pomme de terre",
  "potatoes": "pomme de terre",
  "sweet potato": "patate douce",
  "rice": "riz",
  "pasta": "pâtes",
  "bread": "pain",
  "oil": "huile",
  "olive oil": "huile d'olive",
  "sunflower oil": "huile de tournesol",
  "apple": "pomme",
  "banana": "banane",
  "lemon": "citron",
  "orange": "orange",
  "strawberry": "fraise",
  "carrot": "carotte",
  "broccoli": "brocoli",
  "spinach": "épinards",
  "lettuce": "laitue",
  "mushroom": "champignon",
  "mushrooms": "champignon",
  "corn": "maïs",
  "soy": "soja",
  "soy sauce": "sauce soja",
  "yeast": "levure",
  "vinegar": "vinaigre",
  "honey": "miel",
  "chocolate": "chocolat",
  "cinnamon": "cannelle",
  "ginger": "gingembre",
  "vanilla": "vanille",
  "almond": "amande",
  "almonds": "amande",
  "walnut": "noix",
  "walnuts": "noix",
  "peanut": "arachide",
  "peanuts": "arachide",
  "cashew": "noix de cajou",
  "cashews": "noix de cajou",
  "lentils": "lentilles",
  "chickpeas": "pois chiches",
  "beans": "haricots",
  "oats": "avoine",
  "barley": "orge",
  "rye": "seigle",
  "cream cheese": "fromage à la crème",
  "sour cream": "crème aigre",
  "heavy cream": "crème épaisse",
  "whipping cream": "crème à fouetter",
  "parsley": "persil",
  "cilantro": "coriandre",
  "coriander": "coriandre",
  "thyme": "thym",
  "rosemary": "romarin",
  "basil": "basilic",
  "mint": "menthe",
  "paprika": "paprika",
  "cumin": "cumin",
  "turmeric": "curcuma",
  "nutmeg": "noix de muscade",
  "mustard": "moutarde",
  "ketchup": "ketchup",
  "mayonnaise": "mayonnaise",
  "celery": "céleri",
  "leek": "poireau",
  "zucchini": "courgette",
  "eggplant": "aubergine",
  "bell pepper": "poivron",
  "peas": "petits pois",
  "green beans": "haricots verts",
  "asparagus": "asperge",
  "cauliflower": "chou-fleur",
  "cabbage": "chou",
  "endive": "endive",
  "beet": "betterave",
  "turnip": "navet",
  "radish": "radis",
  "cucumber": "concombre",
  "peach": "pêche",
  "pear": "poire",
  "grape": "raisin",
  "grapes": "raisin",
  "cherry": "cerise",
  "cherries": "cerise",
  "pineapple": "ananas",
  "mango": "mangue",
  "avocado": "avocat",
  "tofu": "tofu",
  "seitan": "seitan",
  "tempeh": "tempeh",

  // --- Synonymes français ---
  "patate": "pomme de terre",
  "frites": "pomme de terre",
  "boeuf": "bœuf",
  "oeuf": "œuf",
  "oeufs": "œufs",
  "yaourt": "yaourt",
  "yoghourt": "yaourt",
  "yogourt": "yaourt",
  "gruyere": "gruyère",
  "comte": "comté",
  "creme fraiche": "crème fraîche",
  "creme": "crème",
  "emmental": "emmental",
  "parmesan": "parmesan",
  "mozzarella": "mozzarella",
  "roquefort": "roquefort",
  "camembert": "camembert",
  "brie": "brie",
  "gouda": "gouda",
  "cheddar": "cheddar",
  "huile d olive": "huile d'olive",
  "huile dolive": "huile d'olive",
  "pates": "pâtes",
  "blé dur": "blé dur",
  "ble": "blé",
  "mais": "maïs",
  "arachide": "arachide",
  "cacahuète": "arachide",
  "cacahuete": "arachide",
  "noisette": "noisette",
  "noisettes": "noisette",
  "pistache": "pistache",
  "pistaches": "pistache",
  "noix de coco": "noix de coco",
  "lait de coco": "lait de coco",
  "saumon fumé": "saumon fumé",
  "saumon fume": "saumon fumé",
  "jambon cru": "jambon cru",
  "jambon blanc": "jambon blanc",
  "lardons": "lardons",
  "lardon": "lardons",
  "pancetta": "pancetta",
  "bacon": "bacon",
  "saucisse": "saucisse",
  "saucisson": "saucisson",
  "chorizo": "chorizo",
  "merguez": "merguez",
  "steak haché": "bœuf haché",
  "steak hache": "bœuf haché",
  "viande hachée": "bœuf haché",
  "levure chimique": "levure chimique",
  "bicarbonate": "bicarbonate de soude",
  "amidon": "amidon",
  "fécule": "fécule",
  "fecule": "fécule",
  "fécule de maïs": "fécule de maïs",
  "maïzena": "fécule de maïs",
  "epinards": "épinards",
  "courgettes": "courgette",
  "aubergines": "aubergine",
  "poivrons": "poivron",
  "tomates cerises": "tomate cerise",
  "tomates": "tomate",
  "carottes": "carotte",
  "oignons": "oignon",
  "champignons": "champignon",
  "asperges": "asperge",
  "haricots verts": "haricots verts",
  "petits pois": "petits pois",
  "celeri": "céleri",
  "poireaux": "poireau",
  "betteraves": "betterave",
  "navets": "navet",
  "radis": "radis",
  "concombres": "concombre",
  "fraises": "fraise",
  "cerises": "cerise",
  "raisins": "raisin",
  "peches": "pêche",
  "abricots": "abricot",
  "abricot": "abricot",
  "prune": "prune",
  "prunes": "prune",
  "figues": "figue",
  "figue": "figue",
  "dattes": "datte",
  "datte": "datte",
  "amandes": "amande",
  "noix": "noix",
  "sauce worcestershire": "sauce worcestershire",
  "sauce soja": "sauce soja",
  "sauce de soja": "sauce soja",
  "vinaigre balsamique": "vinaigre balsamique",
  "vinaigre de cidre": "vinaigre de cidre",
  "bouillon de poulet": "bouillon de poulet",
  "bouillon de légumes": "bouillon de légumes",
  "cube de bouillon": "bouillon",
};

// Mots-clés par catégorie pour deviner la catégorie d'un ingrédient
const CATEGORY_KEYWORDS = {
  laitier:     ["lait", "crème", "beurre", "fromage", "yaourt", "lactose", "caséine", "lactosérum", "whey", "mozzarella", "parmesan", "comté", "gruyère", "gouda", "cheddar", "brie", "camembert", "roquefort", "emmental", "mascarpone", "ricotta", "skyr"],
  cereale:     ["farine", "blé", "seigle", "orge", "avoine", "épeautre", "gluten", "amidon", "fécule", "pâtes", "semoule", "céréale", "flocon", "son de"],
  viande:      ["poulet", "bœuf", "porc", "agneau", "veau", "dinde", "canard", "jambon", "bacon", "lardon", "saucisse", "saucisson", "chorizo", "merguez", "viande", "gelée de porc"],
  poisson:     ["saumon", "thon", "cabillaud", "sole", "truite", "sardine", "anchois", "maquereau", "dorade", "poisson", "crevette", "moule", "huître", "homard", "crabe"],
  legume:      ["carotte", "tomate", "oignon", "ail", "poireau", "courgette", "aubergine", "poivron", "brocoli", "chou", "épinard", "céleri", "betterave", "navet", "radis", "concombre", "laitue", "endive", "champignon", "asperge", "artichaut", "fenouil"],
  fruit:       ["pomme", "poire", "banane", "orange", "citron", "fraise", "cerise", "raisin", "pêche", "abricot", "mangue", "ananas", "kiwi", "melon", "framboise", "figue", "datte", "prune", "avocat"],
  noix:        ["amande", "noisette", "pistache", "cajou", "arachide", "cacahuète", "graine de sésame", "graine de tournesol", "graine de lin", "graine de chia", "noix de coco", "noix de cajou"],
  epice:       ["sel", "poivre", "cannelle", "cumin", "curcuma", "paprika", "coriandre", "gingembre", "muscade", "cardamome", "curry", "thym", "romarin", "basilic", "persil", "menthe", "laurier", "safran", "vanille", "arôme", "moutarde", "vinaigre"],
  additif:     ["phosphate", "carbonate", "nitrite", "nitrate", "sorbate", "benzoate", "citrate", "colorant", "conservateur", "émulsifiant", "stabilisant", "épaississant", "gélifiant", "antioxydant", "lécithine", "carraghénane", "gomme", "pectine", "agar", "cellulose", "maltodextrine", "bicarbonate", "levure chimique", "poudre à lever", "poudres à lever", "acide ascorbique", "acide citrique", "acide sorbique", "tocophérol", "diphosphate"],
  legumineuse: ["lentille", "pois chiche", "haricot", "soja", "fève", "pois cassé", "lupin", "edamame", "tofu", "tempeh"],
  oeuf:        ["œuf", "oeuf", "jaune d'œuf", "blanc d'œuf", "albumine", "ovalbumine"],
  sucre:       ["sucre", "miel", "sirop", "caramel", "fructose", "saccharose", "glucose", "chocolat", "confiture", "dextrose"],
  graisse:     ["huile", "margarine", "saindoux", "graisse végétale", "shortening", "beurre de cacao"],
};

/**
 * Devine la catégorie d'un ingrédient à partir de son nom.
 * @param {string} name - Le nom canonique de l'ingrédient
 * @returns {string} - La catégorie devinée
 */
export function guessCategory(name) {
  if (!name) return "autre";
  const lower = name.toLowerCase();
  // E-numbers (ex: E471, E300b)
  if (/\be\d{3,4}[a-z]?\b/i.test(lower)) return "additif";
  for (const [cat, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    if (keywords.some(kw => lower.includes(kw))) return cat;
  }
  return "autre";
}

/**
 * Normalise un nom d'ingrédient vers sa forme canonique française.
 * @param {string} name - Le nom brut (peut être en anglais ou avoir des variantes)
 * @returns {string} - Le nom canonique en français
 */
export function normalizeIngredientName(name) {
  if (!name || typeof name !== "string") return name;
  const lower = name.toLowerCase().trim().replace(/^_+|_+$/g, "");
  // Recherche exacte
  if (SYNONYMS[lower]) return SYNONYMS[lower];
  // Retourne la version lowercase/trim si pas de synonyme trouvé
  return lower;
}

/**
 * Normalise un tableau d'ingrédients.
 * @param {Array<{nom: string, categorie: string}>} ingredients
 * @returns {Array<{nom: string, categorie: string}>}
 */
export function normalizeIngredients(ingredients) {
  if (!Array.isArray(ingredients)) return ingredients;
  return ingredients.map(ing => ({
    ...ing,
    nom: normalizeIngredientName(ing.nom),
  }));
}
